package tn.esprit.pets.entity;

public enum Town {
    ARIANA, BEJA, BENAROUS, BIZERTE, GABES, GAFSA, JENDOUBA, KAIROUAN, KASSERINE, KEBILI, KEF, MAHDIA, MANOUBA, MEDENINE, MONASTIR, NABEUL,
    SFAX, SIDIBOUZID, SILIANA, SOUSSE, TATAOUINE, TOZEUR, TUNIS, ZAGHOUAN
}
